
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.007100
     time (cpu & wall) for ordering          =        0.046875        0.104144
     time (cpu & wall) for other matrix prep =        0.000000        0.018264
     time (cpu & wall) for value input       =        0.000000        0.002224
     time (cpu & wall) for matrix distrib.   =        0.000000        0.018923
     time (cpu & wall) for numeric factor    =        0.046875        0.431408
     computational rate (gflops) for factor  =       37.971513        4.125830

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      2

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001635
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002948
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011674

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      3

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001668
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003379
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010662
     time (cpu & wall) for numeric factor    =        0.015625        0.116341
     computational rate (gflops) for factor  =      113.914539       15.299157

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      4

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001134
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003843
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010495
     time (cpu & wall) for numeric factor    =        0.046875        0.173392
     computational rate (gflops) for factor  =       37.971513       10.265270

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      5

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003070
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003767
     time (cpu & wall) for matrix distrib.   =        0.000000        0.014938
     time (cpu & wall) for numeric factor    =        0.031250        0.192077
     computational rate (gflops) for factor  =       56.957270        9.266663

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      6

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002155
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003054
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010518
     time (cpu & wall) for numeric factor    =        0.015625        0.121160
     computational rate (gflops) for factor  =      113.914539       14.690613

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      7

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.015625        0.002075
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005775
     time (cpu & wall) for matrix distrib.   =        0.000000        0.013373
     time (cpu & wall) for numeric factor    =        0.015625        0.149074
     computational rate (gflops) for factor  =      113.914539       11.939766

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      8

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002273
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.005054
     time (cpu & wall) for matrix distrib.   =        0.015625        0.013430

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =      9

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002906
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003630
     time (cpu & wall) for matrix distrib.   =        0.015625        0.013708
     time (cpu & wall) for numeric factor    =        0.015625        0.125605
     computational rate (gflops) for factor  =      113.914539       14.170787

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     10

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001922
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.004230
     time (cpu & wall) for matrix distrib.   =        0.000000        0.013062
     time (cpu & wall) for numeric factor    =        0.015625        0.135024
     computational rate (gflops) for factor  =      113.914539       13.182180

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     11

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003275
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003707
     time (cpu & wall) for matrix distrib.   =        0.015625        0.011484

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     12

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001585
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002951
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012005

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     13

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001986
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002962
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011576
     time (cpu & wall) for numeric factor    =        0.031250        0.147520
     computational rate (gflops) for factor  =       56.957270       12.065598

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     14

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001589
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003285
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011035
     time (cpu & wall) for numeric factor    =        0.015625        0.134415
     computational rate (gflops) for factor  =      113.914539       13.241925

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     15

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001696
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002288
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010973
     time (cpu & wall) for numeric factor    =        0.015625        0.122901
     computational rate (gflops) for factor  =      113.914539       14.482519

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     16

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002128
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003464
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012015

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     17

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003750
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002965
     time (cpu & wall) for matrix distrib.   =        0.000000        0.013216

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     18

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001598
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003282
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010902

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     19

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001591
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003706
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011688

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     20

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001248
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002397
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008759

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     21

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001982
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002998
     time (cpu & wall) for matrix distrib.   =        0.015625        0.015013
     time (cpu & wall) for numeric solve     =        0.015625        0.002443
     computational rate (gflops) for solve   =        1.234703        7.896618
     effective I/O rate (GB/sec) for solve   =        4.599991       29.419530

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     22

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002536
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003161
     time (cpu & wall) for matrix distrib.   =        0.000000        0.015191
     time (cpu & wall) for numeric factor    =        0.015625        0.124643
     computational rate (gflops) for factor  =      113.914539       14.280056

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     23

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002522
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003845
     time (cpu & wall) for matrix distrib.   =        0.015625        0.014807
     time (cpu & wall) for numeric factor    =        0.015625        0.128998
     computational rate (gflops) for factor  =      113.914539       13.797981

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     24

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004001
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002213
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010753
     time (cpu & wall) for numeric factor    =        0.015625        0.108347
     computational rate (gflops) for factor  =      113.914539       16.427955

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     25

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001550
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003648
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010674
     time (cpu & wall) for numeric factor    =        0.015625        0.120586
     computational rate (gflops) for factor  =      113.914539       14.760542

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     26

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001674
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002974
     time (cpu & wall) for matrix distrib.   =        0.031250        0.011345
     time (cpu & wall) for numeric factor    =        0.015625        0.114365
     computational rate (gflops) for factor  =      113.914539       15.563456

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     27

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001590
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002982
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012105
     time (cpu & wall) for numeric factor    =        0.031250        0.209038
     computational rate (gflops) for factor  =       56.957270        8.514786
     time (cpu & wall) for numeric solve     =        0.015625        0.002222
     computational rate (gflops) for solve   =        1.234703        8.683543
     effective I/O rate (GB/sec) for solve   =        4.599991       32.351287

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     28

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001588
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.003004
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010727

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     29

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004154
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.015625        0.003121
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011500
     time (cpu & wall) for numeric factor    =        0.015625        0.121620
     computational rate (gflops) for factor  =      113.914539       14.635037

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     30

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001675
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003631
     time (cpu & wall) for matrix distrib.   =        0.000000        0.013493
     time (cpu & wall) for numeric factor    =        0.015625        0.135273
     computational rate (gflops) for factor  =      113.914539       13.157993

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     31

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002325
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002245
     time (cpu & wall) for matrix distrib.   =        0.015625        0.009045
     time (cpu & wall) for numeric factor    =        0.031250        0.124730
     computational rate (gflops) for factor  =       56.957270       14.270152

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     32

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003810
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002215
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008722

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     33

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001237
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003103
     time (cpu & wall) for matrix distrib.   =        0.000000        0.014090
     time (cpu & wall) for numeric factor    =        0.031250        0.135952
     computational rate (gflops) for factor  =       56.957270       13.092248

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     34

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001640
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003905
     time (cpu & wall) for matrix distrib.   =        0.000000        0.014120

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     35

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001957
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007438
     time (cpu & wall) for matrix distrib.   =        0.000000        0.017078
     time (cpu & wall) for numeric factor    =        0.015625        0.120204
     computational rate (gflops) for factor  =      113.914539       14.807462

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     36

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001666
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.007793
     time (cpu & wall) for matrix distrib.   =        0.000000        0.013418
     time (cpu & wall) for numeric factor    =        0.015625        0.129258
     computational rate (gflops) for factor  =      113.914539       13.770205

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     37

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002210
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003104
     time (cpu & wall) for matrix distrib.   =        0.031250        0.012773

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     38

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001124
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.004324
     time (cpu & wall) for matrix distrib.   =        0.015625        0.017344

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     39

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001602
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002440
     time (cpu & wall) for matrix distrib.   =        0.015625        0.009810

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     40

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004615
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002980
     time (cpu & wall) for matrix distrib.   =        0.015625        0.010723
     time (cpu & wall) for numeric factor    =        0.015625        0.114559
     computational rate (gflops) for factor  =      113.914539       15.537127

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     41

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001223
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.004520
     time (cpu & wall) for matrix distrib.   =        0.000000        0.016026

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     42

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002826
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002203
     time (cpu & wall) for matrix distrib.   =        0.000000        0.010800
     time (cpu & wall) for numeric factor    =        0.015625        0.144501
     computational rate (gflops) for factor  =      113.914539       12.317629

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     43

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003929
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.004548
     time (cpu & wall) for matrix distrib.   =        0.000000        0.018595
     time (cpu & wall) for numeric factor    =        0.015625        0.115136
     computational rate (gflops) for factor  =      113.914539       15.459210

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     44

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001204
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.004788
     time (cpu & wall) for matrix distrib.   =        0.015625        0.024862
     time (cpu & wall) for numeric factor    =        0.031250        0.140071
     computational rate (gflops) for factor  =       56.957270       12.707196

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     45

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.003270
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003947
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012121
     time (cpu & wall) for numeric factor    =        0.031250        0.150587
     computational rate (gflops) for factor  =       56.957270       11.819866

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     46

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.004429
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002978
     time (cpu & wall) for matrix distrib.   =        0.000000        0.014709

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     47

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001145
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002805
     time (cpu & wall) for matrix distrib.   =        0.000000        0.008699
     time (cpu & wall) for numeric factor    =        0.015625        0.120298
     computational rate (gflops) for factor  =      113.914539       14.795842

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     48

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.002123
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002247
     time (cpu & wall) for matrix distrib.   =        0.015625        0.008366
     time (cpu & wall) for numeric factor    =        0.015625        0.122078
     computational rate (gflops) for factor  =      113.914539       14.580167

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     49

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001717
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.003018
     time (cpu & wall) for matrix distrib.   =        0.000000        0.012076
     time (cpu & wall) for numeric factor    =        0.031250        0.165491
     computational rate (gflops) for factor  =       56.957270       10.755343

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     50

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001403
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002227
     time (cpu & wall) for matrix distrib.   =        0.015625        0.012814

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB





  Performance statistics for DSP solver: icalls =     51

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =           19360
     no. of nonzeroes in lower triangle of a =          498324
     no. of nonzeroes in the factor l        =         5185724
     ratio of nonzeroes in factor (min/max)  =          0.8716
     number of super nodes                   =             646
     maximum order of a front matrix         =             808
     maximum size of a front matrix          =          326836
     maximum size of a front trapezoid       =          176410
     no. of floating point ops for factor    =      1.7799D+09
     no. of floating point ops for solve     =      1.9292D+07
     ratio of flops for factor (min/max)     =          0.8575
     ratio of allocated memory (max/min)     =          1.1724
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of processes used                =               4
     number of threads per process used      =               1
     number of cores used                    =               4
     time (cpu & wall) for structure input   =        0.000000        0.001850
     time (cpu & wall) for ordering          =        0.000000        0.000000
     time (cpu & wall) for other matrix prep =        0.000000        0.000000
     time (cpu & wall) for value input       =        0.000000        0.002953
     time (cpu & wall) for matrix distrib.   =        0.000000        0.011476

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         98304.        1. MB         74930.        1. MB
                95-   1         98304.        1. MB         68286.        1. MB
                95-   2         98304.        1. MB         75423.        1. MB
                95-   3         98304.        1. MB         71078.        1. MB

                -------     ----------     --------     ----------     --------
                Totals:        393216.        3. MB        289717.        2. MB


  Solver Memory allocated on core    0       =       20.492 MB
  Solver Memory allocated on core    1       =       17.478 MB
  Solver Memory allocated on core    2       =       20.023 MB
  Solver Memory allocated on core    3       =       18.586 MB
  Total Solver Memory allocated by all cores =       76.580 MB

